#define DYNAMIC_KEYMAP_LAYER_COUNT 20

#undef MASTER_RIGHT
#define MASTER_LEFT
#define COMBO_TERM 5000
#define MANUFACTURER "Bastard Keyboards"

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX

#define TAPPING_TERM 200
